import "./globals.css";
import type { Metadata } from "next";
import { dmSans, poppins } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout of the application
const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${poppins.variable} pb-52 font-sans`}>{children}</body>
    </html>
  );
};

export default RootLayout;
