const booths = [
  {
    id: 1,
    category: "Platinum",
    size: "54",
    dimensions: "9*6",
    price: "$39,000",
    image: "images/booths/stand1.jpg",
    description: "Platinum 54",
    inclusions: "Included... Platinum 54",
    remaining: "1",
    header: "header platinum 1",
  },
  {
    id: 2,
    category: "Platinum",
    size: "36",
    dimensions: "6*6",
    price: "$33,000",
    image: "images/booths/stand1.jpg",
    description: "Platinum 36",
    inclusions: "Included... Platinum 36",
    remaining: "12",
    header: "header platinum 2",
  },
  {
    id: 3,
    category: "Gold",
    size: "36",
    dimensions: "6*6",
    price: "$29,000",
    image: "images/booths/stand1.jpg",
    description: "Gold 36",
    inclusions: "Included...  Gold 26",
    remaining: "3",
    header: "header gold 1",
  },
  {
    id: 4,
    category: "Gold",
    size: "27",
    dimensions: "9*3",
    price: "$20,000",
    image: "images/booths/stand1.jpg",
    description: "Gold 27",
    inclusions: "Included...  Gold 27",
    remaining: "4",
    header: "header gold 2",
  },
  {
    id: 5,
    category: "Gold",
    size: "18",
    dimensions: "6*3 / 9*2",
    price: "$17,000",
    image: "images/booths/stand1.jpg",
    description: "Gold 18",
    inclusions: "Included...  Gold 18",
    remaining: "5",
    header: "header gold 3",
  },
  {
    id: 6,
    category: "Silver",
    size: "18",
    dimensions: "6*3 / 9*2",
    price: "$12,000",
    image: "images/booths/stand1.jpg",
    description: "Silver 18",
    inclusions: "Included...  silver 18",
    remaining: "6",
    header: "header silver 1",
  },
  {
    id: 7,
    category: "Silver",
    size: "9",
    dimensions: "3*3",
    price: "$5,000",
    image: "images/booths/stand1.jpg",
    description: "Silver 9",
    inclusions: "Included... silver 9 ",
    remaining: "7",
    header: "header silver 2",
  },
  {
    id: 8,
    category: "Silver",
    size: "8",
    dimensions: "4*2",
    price: "$4000",
    image: "images/booths/stand1.jpg",
    description: "Silver 8",
    inclusions: "Included... silver 8",
    remaining: "8",
    header: "header silver 3",
  },
];

export default booths;
